[versions]
koin = "4.1.2-Beta1"
kotlin = "2.2.21"
ktor = "3.3.2"
logback = "1.4.14"
admin = "9.7.0"
mongo = "5.6.0"
dotenv = "6.4.1"
cloudinary="1.39.0"
lettuce="6.3.2.RELEASE"
[libraries]
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
bson = { module = "org.mongodb:bson", version.ref = "mongo" }
ktor-server-websockets = { module = "io.ktor:ktor-server-websockets", version.ref = "ktor" }
koin-ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koin" }
koin-logger-slf4j = { module = "io.insert-koin:koin-logger-slf4j", version.ref = "koin" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
ktor-server-config-yaml = { module = "io.ktor:ktor-server-config-yaml", version.ref = "ktor" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
firebase-admin = {module = "com.google.firebase:firebase-admin" , version.ref = "admin"}
mongodb-driver-core = { module = "org.mongodb:mongodb-driver-core", version.ref = "mongo" }
mongodb-driver-sync = { module = "org.mongodb:mongodb-driver-sync", version.ref = "mongo" }
mongodb-driver-kotlin-coroutine = { module = "org.mongodb:mongodb-driver-kotlin-coroutine" , version.ref = "mongo"}
dotenv-kotlin = {module = "io.github.cdimascio:dotenv-kotlin" ,version.ref = "dotenv"}
ktor-client-core={module = "io.ktor:ktor-client-core" , version.ref = "ktor" }
ktor-client-cio = {module = "io.ktor:ktor-client-cio" , version.ref="ktor"}
ktor-client-content-negotiation= {module = "io.ktor:ktor-client-content-negotiation" , version.ref= "ktor"}
cloudinary-sdk={module="com.cloudinary:cloudinary-http44" , version.ref="cloudinary"}
ktor-rate-limiter ={module = "io.ktor:ktor-server-rate-limit" , version.ref="ktor"}
lettuce-core = {module="io.lettuce:lettuce-core" , version.ref="lettuce"}
[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
